// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scaffold.Infrastructure.Data;

#nullable disable

namespace Scaffold.Infrastructure.Migrations
{
    [DbContext(typeof(ScaffoldDbContext))]
    [Migration("20260416210253_AddPlatformFields")]
    partial class AddPlatformFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Scaffold.Core.Models.AssessmentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CompatibilityScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("AssessmentReports");
                });

            modelBuilder.Entity("Scaffold.Core.Models.ConnectionInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KeyVaultSecretUri")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("MigrationProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("TrustServerCertificate")
                        .HasColumnType("bit");

                    b.Property<bool>("UseSqlAuthentication")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MigrationProjectId")
                        .IsUnique()
                        .HasFilter("[MigrationProjectId] IS NOT NULL");

                    b.ToTable("ConnectionInfos");
                });

            modelBuilder.Entity("Scaffold.Core.Models.MigrationPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExcludedObjects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExistingTargetConnectionString")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IncludedObjects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MigrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcePlatform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetPlatform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseExistingTarget")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("MigrationPlans");
                });

            modelBuilder.Entity("Scaffold.Core.Models.MigrationProgressRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentTable")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("MigrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PercentComplete")
                        .HasColumnType("float");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("RowsProcessed")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MigrationId");

                    b.ToTable("MigrationProgressRecords");
                });

            modelBuilder.Entity("Scaffold.Core.Models.MigrationProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MigrationProjects");
                });

            modelBuilder.Entity("Scaffold.Core.Models.MigrationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DataSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RowsMigrated")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("MigrationResults");
                });

            modelBuilder.Entity("Scaffold.Core.Models.AssessmentReport", b =>
                {
                    b.HasOne("Scaffold.Core.Models.MigrationProject", null)
                        .WithOne("Assessment")
                        .HasForeignKey("Scaffold.Core.Models.AssessmentReport", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Scaffold.Core.Models.TierRecommendation", "Recommendation", b1 =>
                        {
                            b1.Property<Guid>("AssessmentReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ComputeSize")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Dtus")
                                .HasColumnType("int");

                            b1.Property<decimal>("EstimatedMonthlyCostUsd")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Reasoning")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RecommendedRegion")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ServiceTier")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("StorageGb")
                                .HasColumnType("int");

                            b1.Property<int?>("VCores")
                                .HasColumnType("int");

                            b1.HasKey("AssessmentReportId");

                            b1.ToTable("AssessmentReports");

                            b1.ToJson("Recommendation");

                            b1.WithOwner()
                                .HasForeignKey("AssessmentReportId");
                        });

                    b.OwnsMany("Scaffold.Core.Models.CompatibilityIssue", "CompatibilityIssues", b1 =>
                        {
                            b1.Property<Guid>("AssessmentReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DocUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsBlocking")
                                .HasColumnType("bit");

                            b1.Property<string>("IssueType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ObjectName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Severity")
                                .HasColumnType("int");

                            b1.HasKey("AssessmentReportId", "Id");

                            b1.ToTable("AssessmentReports");

                            b1.ToJson("CompatibilityIssues");

                            b1.WithOwner()
                                .HasForeignKey("AssessmentReportId");
                        });

                    b.OwnsOne("Scaffold.Core.Models.DataProfile", "DataProfile", b1 =>
                        {
                            b1.Property<Guid>("AssessmentReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("TotalRowCount")
                                .HasColumnType("bigint");

                            b1.Property<long>("TotalSizeBytes")
                                .HasColumnType("bigint");

                            b1.HasKey("AssessmentReportId");

                            b1.ToTable("AssessmentReports");

                            b1.ToJson("DataProfile");

                            b1.WithOwner()
                                .HasForeignKey("AssessmentReportId");

                            b1.OwnsMany("Scaffold.Core.Models.TableProfile", "Tables", b2 =>
                                {
                                    b2.Property<Guid>("DataProfileAssessmentReportId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    b2.Property<long>("RowCount")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("SchemaName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<long>("SizeBytes")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("TableName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("DataProfileAssessmentReportId", "Id");

                                    b2.ToTable("AssessmentReports");

                                    b2.WithOwner()
                                        .HasForeignKey("DataProfileAssessmentReportId");
                                });

                            b1.Navigation("Tables");
                        });

                    b.OwnsOne("Scaffold.Core.Models.PerformanceProfile", "Performance", b1 =>
                        {
                            b1.Property<Guid>("AssessmentReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("AvgCpuPercent")
                                .HasColumnType("float");

                            b1.Property<double>("AvgIoMbPerSecond")
                                .HasColumnType("float");

                            b1.Property<long>("MaxDatabaseSizeMb")
                                .HasColumnType("bigint");

                            b1.Property<long>("MemoryUsedMb")
                                .HasColumnType("bigint");

                            b1.HasKey("AssessmentReportId");

                            b1.ToTable("AssessmentReports");

                            b1.ToJson("Performance");

                            b1.WithOwner()
                                .HasForeignKey("AssessmentReportId");
                        });

                    b.OwnsOne("Scaffold.Core.Models.SchemaInventory", "Schema", b1 =>
                        {
                            b1.Property<Guid>("AssessmentReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IndexCount")
                                .HasColumnType("int");

                            b1.Property<int>("StoredProcedureCount")
                                .HasColumnType("int");

                            b1.Property<int>("TableCount")
                                .HasColumnType("int");

                            b1.Property<int>("TriggerCount")
                                .HasColumnType("int");

                            b1.Property<int>("ViewCount")
                                .HasColumnType("int");

                            b1.HasKey("AssessmentReportId");

                            b1.ToTable("AssessmentReports");

                            b1.ToJson("Schema");

                            b1.WithOwner()
                                .HasForeignKey("AssessmentReportId");

                            b1.OwnsMany("Scaffold.Core.Models.SchemaObject", "Objects", b2 =>
                                {
                                    b2.Property<Guid>("SchemaInventoryAssessmentReportId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ObjectType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ParentObjectName")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Schema")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("SubType")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("SchemaInventoryAssessmentReportId", "Id");

                                    b2.ToTable("AssessmentReports");

                                    b2.WithOwner()
                                        .HasForeignKey("SchemaInventoryAssessmentReportId");
                                });

                            b1.Navigation("Objects");
                        });

                    b.Navigation("CompatibilityIssues");

                    b.Navigation("DataProfile")
                        .IsRequired();

                    b.Navigation("Performance")
                        .IsRequired();

                    b.Navigation("Recommendation")
                        .IsRequired();

                    b.Navigation("Schema")
                        .IsRequired();
                });

            modelBuilder.Entity("Scaffold.Core.Models.ConnectionInfo", b =>
                {
                    b.HasOne("Scaffold.Core.Models.MigrationProject", null)
                        .WithOne("SourceConnection")
                        .HasForeignKey("Scaffold.Core.Models.ConnectionInfo", "MigrationProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scaffold.Core.Models.MigrationPlan", b =>
                {
                    b.HasOne("Scaffold.Core.Models.MigrationProject", null)
                        .WithOne("MigrationPlan")
                        .HasForeignKey("Scaffold.Core.Models.MigrationPlan", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Scaffold.Core.Models.MigrationScript", "PostMigrationScripts", b1 =>
                        {
                            b1.Property<Guid>("MigrationPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("bit");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<int>("Phase")
                                .HasColumnType("int");

                            b1.Property<string>("ScriptId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ScriptType")
                                .HasColumnType("int");

                            b1.Property<string>("SqlContent")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MigrationPlanId", "Id");

                            b1.ToTable("MigrationPlans");

                            b1.ToJson("PostMigrationScriptsJson");

                            b1.WithOwner()
                                .HasForeignKey("MigrationPlanId");
                        });

                    b.OwnsMany("Scaffold.Core.Models.MigrationScript", "PreMigrationScripts", b1 =>
                        {
                            b1.Property<Guid>("MigrationPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("bit");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<int>("Phase")
                                .HasColumnType("int");

                            b1.Property<string>("ScriptId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ScriptType")
                                .HasColumnType("int");

                            b1.Property<string>("SqlContent")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MigrationPlanId", "Id");

                            b1.ToTable("MigrationPlans");

                            b1.ToJson("PreMigrationScriptsJson");

                            b1.WithOwner()
                                .HasForeignKey("MigrationPlanId");
                        });

                    b.OwnsOne("Scaffold.Core.Models.TierRecommendation", "TargetTier", b1 =>
                        {
                            b1.Property<Guid>("MigrationPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ComputeSize")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Dtus")
                                .HasColumnType("int");

                            b1.Property<decimal>("EstimatedMonthlyCostUsd")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Reasoning")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RecommendedRegion")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ServiceTier")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("StorageGb")
                                .HasColumnType("int");

                            b1.Property<int?>("VCores")
                                .HasColumnType("int");

                            b1.HasKey("MigrationPlanId");

                            b1.ToTable("MigrationPlans");

                            b1.ToJson("TargetTier");

                            b1.WithOwner()
                                .HasForeignKey("MigrationPlanId");
                        });

                    b.Navigation("PostMigrationScripts");

                    b.Navigation("PreMigrationScripts");

                    b.Navigation("TargetTier")
                        .IsRequired();
                });

            modelBuilder.Entity("Scaffold.Core.Models.MigrationResult", b =>
                {
                    b.HasOne("Scaffold.Core.Models.MigrationProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Scaffold.Core.Models.ValidationResult", "Validations", b1 =>
                        {
                            b1.Property<Guid>("MigrationResultId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<bool>("ChecksumMatch")
                                .HasColumnType("bit");

                            b1.Property<long>("SourceRowCount")
                                .HasColumnType("bigint");

                            b1.Property<string>("TableName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long>("TargetRowCount")
                                .HasColumnType("bigint");

                            b1.HasKey("MigrationResultId", "Id");

                            b1.ToTable("MigrationResults");

                            b1.ToJson("Validations");

                            b1.WithOwner()
                                .HasForeignKey("MigrationResultId");
                        });

                    b.Navigation("Validations");
                });

            modelBuilder.Entity("Scaffold.Core.Models.MigrationProject", b =>
                {
                    b.Navigation("Assessment");

                    b.Navigation("MigrationPlan");

                    b.Navigation("SourceConnection");
                });
#pragma warning restore 612, 618
        }
    }
}
