using System.Text.RegularExpressions;

namespace Scaffold.Migration.PostgreSql;

/// <summary>
/// Maps SQL Server data types to their PostgreSQL equivalents,
/// including precision/scale handling, identity mapping, and default expressions.
/// </summary>
public static class DataTypeMapper
{
    private static readonly Dictionary<string, string> TypeMap = new(StringComparer.OrdinalIgnoreCase)
    {
        // Integer types
        ["int"] = "integer",
        ["bigint"] = "bigint",
        ["smallint"] = "smallint",
        ["tinyint"] = "smallint",
        ["bit"] = "boolean",

        // String types
        ["text"] = "text",
        ["ntext"] = "text",

        // Date/time types
        ["datetime"] = "timestamp",
        ["datetime2"] = "timestamp",
        ["datetimeoffset"] = "timestamptz",
        ["smalldatetime"] = "timestamp(0)",
        ["date"] = "date",
        ["time"] = "time",

        // Numeric types
        ["money"] = "numeric(19,4)",
        ["smallmoney"] = "numeric(10,4)",
        ["float"] = "double precision",
        ["real"] = "real",

        // Binary types
        ["image"] = "bytea",

        // Special types
        ["uniqueidentifier"] = "uuid",
        ["xml"] = "xml",
        ["sql_variant"] = "text",
        ["geography"] = "text",
        ["geometry"] = "text",
        ["hierarchyid"] = "text",
        ["rowversion"] = "bytea",
        ["timestamp"] = "bytea",
        ["sysname"] = "varchar(128)",
    };

    private static readonly Dictionary<string, string> WarningTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        ["sql_variant"] = "sql_variant has no direct PostgreSQL equivalent; mapped to text with potential data loss.",
        ["geography"] = "PostGIS geometry type recommended. Mapped to text as fallback.",
        ["geometry"] = "PostGIS geometry type recommended. Mapped to text as fallback.",
        ["hierarchyid"] = "No PostgreSQL equivalent; stored as string representation.",
        ["rowversion"] = "No PostgreSQL equivalent for auto-incrementing rowversion. Mapped to bytea.",
        ["timestamp"] = "No PostgreSQL equivalent for auto-incrementing rowversion. Mapped to bytea.",
    };

    private static readonly Regex ParameterizedTypeRegex = new(
        @"^(\w+)\s*\(\s*(MAX|\d+)(?:\s*,\s*(\d+))?\s*\)$",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    /// <summary>
    /// Maps a SQL Server data type to its PostgreSQL equivalent.
    /// Handles parameterized types like varchar(50), decimal(18,2), datetime2(3), etc.
    /// </summary>
    public static string MapType(string sqlServerType, int? maxLength = null, int? precision = null, int? scale = null)
    {
        var normalizedType = sqlServerType.Trim();

        // Try to parse parameterized types like "varchar(50)" or "decimal(18,2)"
        var match = ParameterizedTypeRegex.Match(normalizedType);
        if (match.Success)
        {
            var baseType = match.Groups[1].Value.ToLowerInvariant();
            var param1Str = match.Groups[2].Value;
            var param2Str = match.Groups[3].Success ? match.Groups[3].Value : null;

            return MapParameterizedType(baseType, param1Str, param2Str);
        }

        // Use explicit parameters if provided
        var typeLower = normalizedType.ToLowerInvariant();

        if (maxLength.HasValue || precision.HasValue)
        {
            return MapParameterizedType(
                typeLower,
                maxLength.HasValue ? (maxLength.Value == -1 ? "MAX" : maxLength.Value.ToString()) : precision?.ToString(),
                scale?.ToString());
        }

        // Direct lookup
        if (TypeMap.TryGetValue(typeLower, out var pgType))
            return pgType;

        // Fallback: return as-is (unknown type)
        return typeLower;
    }

    /// <summary>
    /// Returns true if the SQL Server type needs special handling and outputs a warning message.
    /// </summary>
    public static bool HasWarning(string sqlServerType, out string warning)
    {
        var normalizedType = sqlServerType.Trim();

        // Parse out the base type if parameterized
        var match = ParameterizedTypeRegex.Match(normalizedType);
        var baseType = match.Success ? match.Groups[1].Value : normalizedType;

        if (WarningTypes.TryGetValue(baseType, out var msg))
        {
            warning = msg;
            return true;
        }

        warning = string.Empty;
        return false;
    }

    /// <summary>
    /// Maps a SQL Server identity column to its PostgreSQL GENERATED ALWAYS AS IDENTITY equivalent.
    /// </summary>
    public static string MapIdentity(string sqlServerType)
    {
        var typeLower = sqlServerType.Trim().ToLowerInvariant();

        return typeLower switch
        {
            "int" or "integer" => "integer GENERATED BY DEFAULT AS IDENTITY",
            "bigint" => "bigint GENERATED BY DEFAULT AS IDENTITY",
            "smallint" => "smallint GENERATED BY DEFAULT AS IDENTITY",
            "tinyint" => "smallint GENERATED BY DEFAULT AS IDENTITY",
            _ => $"{MapType(sqlServerType)} GENERATED BY DEFAULT AS IDENTITY"
        };
    }

    /// <summary>
    /// Returns the SERIAL-family type for older PostgreSQL compatibility.
    /// </summary>
    public static string MapIdentitySerial(string sqlServerType)
    {
        var typeLower = sqlServerType.Trim().ToLowerInvariant();

        return typeLower switch
        {
            "int" or "integer" => "SERIAL",
            "bigint" => "BIGSERIAL",
            "smallint" or "tinyint" => "SMALLSERIAL",
            _ => "SERIAL"
        };
    }

    /// <summary>
    /// Maps a SQL Server default expression to its PostgreSQL equivalent.
    /// </summary>
    public static string? MapDefaultExpression(string? sqlServerDefault)
    {
        if (string.IsNullOrWhiteSpace(sqlServerDefault))
            return null;

        // Strip wrapping parentheses common in SQL Server defaults: ((0)), (getdate()), etc.
        var expr = sqlServerDefault.Trim();
        while (expr.StartsWith('(') && expr.EndsWith(')') && expr.Length > 2)
            expr = expr[1..^1];

        var exprLower = expr.ToLowerInvariant();

        // Function mappings
        return exprLower switch
        {
            "getdate()" => "CURRENT_TIMESTAMP",
            "getutcdate()" => "(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')",
            "sysdatetime()" => "CURRENT_TIMESTAMP",
            "sysutcdatetime()" => "(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')",
            "sysdatetimeoffset()" => "CURRENT_TIMESTAMP",
            "newid()" => "gen_random_uuid()",
            "newsequentialid()" => "gen_random_uuid()",
            "user_name()" => "CURRENT_USER",
            "suser_sname()" => "CURRENT_USER",
            "host_name()" => "inet_client_addr()",
            _ => MapLiteralDefault(expr)
        };
    }

    private static string MapParameterizedType(string baseType, string? param1, string? param2)
    {
        var isMax = string.Equals(param1, "MAX", StringComparison.OrdinalIgnoreCase);

        return baseType switch
        {
            // String types with length
            "varchar" or "nvarchar" => isMax ? "text" : $"varchar({param1})",
            "char" or "nchar" => isMax ? "text" : $"char({param1})",

            // Numeric types with precision/scale
            "decimal" or "numeric" => param2 != null ? $"numeric({param1},{param2})" : $"numeric({param1})",

            // Date/time types with precision (PostgreSQL max fractional-seconds precision is 6)
            "datetime2" => param1 != null ? $"timestamp({ClampTemporalPrecision(param1)})" : "timestamp",
            "datetimeoffset" => param1 != null ? $"timestamptz({ClampTemporalPrecision(param1)})" : "timestamptz",
            "time" => param1 != null ? $"time({ClampTemporalPrecision(param1)})" : "time",

            // Binary types
            "varbinary" => "bytea",
            "binary" => "bytea",

            // Float with precision (SQL Server float(n) → double precision or real)
            "float" => int.TryParse(param1, out var fp) && fp <= 24 ? "real" : "double precision",

            // Fallback to direct lookup for the base type
            _ => TypeMap.TryGetValue(baseType, out var pgType) ? pgType : baseType
        };
    }

    /// <summary>
    /// Clamps a temporal precision string to the PostgreSQL range of 0–6.
    /// SQL Server supports datetime2(7) (100ns), but PostgreSQL only supports 0–6 (microseconds).
    /// Negative values from corrupted metadata are clamped to 0.
    /// </summary>
    private static string ClampTemporalPrecision(string precision)
        => int.TryParse(precision, out var p) ? Math.Clamp(p, 0, 6).ToString() : precision;

    private static string MapLiteralDefault(string expr)
    {
        // Numeric literals
        if (int.TryParse(expr, out _) || decimal.TryParse(expr, out _))
            return expr;

        // String literals: N'...' → '...'
        if (expr.StartsWith("N'", StringComparison.OrdinalIgnoreCase) && expr.EndsWith("'"))
            return expr[1..]; // remove the N prefix

        // Already a plain string literal
        if (expr.StartsWith("'") && expr.EndsWith("'"))
            return expr;

        // Pass through as-is
        return expr;
    }
}